/* One page per search term. Every page carries the greeting board generator.
   Keep claims true to what the app does today. */

export const GROUPS = {
  service: "Meet and greet",
  tool: "Tools",
  guide: "Guides",
  pro: "For business",
  home: "For families",
};

export const PAGES = [
  // ── Industry terms ─────────────────────────────
  {
    slug: "airport-meet-and-greet",
    group: "service",
    nav: "Airport meet and greet",
    title: "Airport Meet and Greet App · Find Your Passenger at Arrivals",
    description: "Run every airport meet and greet from your phone: one link for the passenger, landed and ready alerts, a live map to the exit and a digital name board.",
    eyebrow: "Airport meet and greet",
    h1: "Airport meet and greet, without the guessing.",
    lede: "Send your passenger one link. They tap when they land and when they're out. You follow them to the exit and hold up a sign they can't miss.",
    top: "Welcome",
    blocks: [
      { h: "What a meet and greet needs", p: ["Three things go wrong at Arrivals: you don't know when they're really out, they don't know where you're standing, and two people look for each other in a crowd of two hundred. Arigreet fixes each one with a single tap on their side and a clear screen on yours."] },
      { h: "How it runs", list: ["Add their name, flight and where you'll wait.", "Send the link on WhatsApp, Messages or email. It opens in any browser.", "They tap I've landed, Collecting my bags and I'm ready. Your phone buzzes each time.", "You both see each other on a live map, then a big arrow points the way.", "Your phone becomes a name board. They can make it flash from their phone."] },
      { h: "Why passengers like it", p: ["Nothing to install, no account, and the page speaks their language: English, Greek, French, Spanish, Italian, German or Portuguese. Taps made with no signal wait on the phone and send when it comes back."] },
    ],
    faq: [
      ["Is Arigreet a meet and greet service?", "It's the app that runs one. You or your driver still meets the passenger; Arigreet handles the timing, the finding and the sign."],
      ["Does the passenger need to download anything?", "No. The link opens in their phone's browser."],
      ["Can I use it for one-off pickups?", "Yes. Families use it for a single arrival; drivers and hotels use it every day."],
    ],
  },
  {
    slug: "meet-and-assist",
    group: "service",
    nav: "Meet and assist service",
    title: "Meet and Assist Service App · Arrival Alerts and Live Finding",
    description: "Give your meet and assist team live arrival alerts, a passenger locator with no download and a digital name board for the arrivals hall.",
    eyebrow: "Meet and assist",
    h1: "Meet and assist, with the passenger in the loop.",
    lede: "Your agent knows the moment the guest lands, collects bags and walks out. The guest sees who's coming for them and where.",
    top: "Meet and assist",
    blocks: [
      { h: "For agents on the floor", p: ["Each guest gets their own pickup link. Your agent sees every status on one list, opens the live map when the guest is ready, and turns their phone into a name board at the gate or in the hall."] },
      { h: "For the guest", p: ["They see their agent's name, photo and where to meet. One button at a time: I've landed, Collecting my bags, I'm ready. If they get lost, I can't find my greeter lights up the agent's board."] },
      { h: "Privacy your clients will ask about", p: ["Location is shared only after the guest taps I'm ready, only with their agent, and it's deleted when both confirm they've met."] },
    ],
    faq: [
      ["Can several agents use it?", "Each agent signs in on their own phone and manages their own pickups."],
      ["Does it work for VIP and fast-track services?", "Yes. Put the meeting point in the pickup, for example the aircraft door or the fast-track lane, and the guest sees it."],
      ["Which languages does the guest page support?", "English, Greek, French, Spanish, Italian, German and Portuguese."],
    ],
  },
  {
    slug: "airport-arrival-concierge",
    group: "service",
    nav: "Airport arrival concierge",
    title: "Airport Arrival Concierge App · Greet Guests at Arrivals",
    description: "A calm arrival for every guest: personal pickup page, live arrival alerts, a live map to the exit and a digital welcome board.",
    eyebrow: "Arrival concierge",
    h1: "A concierge welcome from the moment they land.",
    lede: "Your guest opens a page with your name, your photo and where you'll be. You know when they're through and walking out.",
    top: "Welcome to the city",
    blocks: [
      { h: "The first five minutes matter", p: ["A tired guest walking out into a crowd decides how the whole trip feels. A clear page that says who is meeting them, where, and that you already know they've landed takes the stress out of it."] },
      { h: "What your guest sees", list: ["Your name, photo and company.", "The exact meeting point and any landmark.", "Your car, colour and plate if you're driving.", "A live note when you're on your way, running late or at Arrivals."] },
      { h: "What you see", list: ["Opened the link, landed, collecting bags, ready.", "A live map, then a finding arrow with the distance in metres.", "A full-screen welcome board with their name."] },
    ],
    faq: [
      ["Can I add my company name?", "Yes. It shows on the guest's page and you can put it above their name on the board."],
      ["What if their flight is late?", "With live flight tracking turned on, you see delays and the new arrival time."],
      ["Can the guest call me?", "Yes, if you add your number. There's no chat to manage."],
    ],
  },
  {
    slug: "airport-pickup-coordination",
    group: "service",
    nav: "Airport pickup coordination",
    title: "Airport Pickup Coordination · One Link for Driver and Passenger",
    description: "Coordinate airport pickups without the phone calls: landed, bags and ready alerts, live location for both sides and a shared meeting point.",
    eyebrow: "Pickup coordination",
    h1: "Coordinate airport pickups without ten phone calls.",
    lede: "Both sides see the same pickup: the flight, the meeting point and where each person is. Every update is one tap.",
    top: "Your pickup",
    blocks: [
      { h: "Where pickups fall apart", p: ["Most pickups fail on small things: the wrong terminal, a driver circling because nobody said bags were slow, a passenger waiting at a different door. Arigreet puts all of that on one page both people can see."] },
      { h: "Updates both ways", list: ["Passenger: I've landed, Collecting my bags, I'm ready, I can't find you.", "Greeter: On my way, Running late (10, 20 or 30 minutes), At Arrivals.", "Both: I'm at the meeting point, We met."] },
      { h: "When signal drops", p: ["Arrivals halls are full of dead spots. Taps wait on the phone and send as soon as there's a bar of signal, and the passenger can still see the saved meeting point."] },
    ],
    faq: [
      ["Does it replace messaging?", "For the pickup, yes. One-tap updates are faster to send and easier to read than texts."],
      ["Can I change the meeting point?", "Yes. The passenger sees a notice that it changed."],
      ["Does it track flights?", "Yes, with live flight data turned on: delays, new arrival times and landing."],
    ],
  },
  {
    slug: "passenger-greeting-service",
    group: "service",
    nav: "Passenger greeting service",
    title: "Passenger Greeting Service App · Name Board and Live Finding",
    description: "Greet passengers properly: a personal pickup link, arrival alerts and a bright digital name board they can make flash from their phone.",
    eyebrow: "Passenger greeting",
    h1: "Greet every passenger by name.",
    lede: "Your phone becomes the sign. Their phone tells you when to hold it up.",
    top: "Welcome",
    blocks: [
      { h: "A sign that finds them", p: ["Paper signs get lost in a row of fifty. The GreetBoard fills your screen with their name in huge letters, and the passenger can make it flash from their phone so they spot you first."] },
      { h: "Timed to the minute", p: ["You hold the sign up when they tap I'm ready, not forty minutes before. Until then your phone is free."] },
      { h: "Made for every arrival", p: ["Business travellers, families with children, guests who don't speak the language. The page is short, clear and in their language."] },
    ],
    faq: [
      ["Can I print the sign instead?", "Yes. Use the generator on this page and download it as an image."],
      ["What does flashing do?", "The passenger taps a button and your board pulses brightly so they can find it in the crowd."],
      ["Does it work in landscape?", "Yes. Turn your phone and the name grows to fill the screen."],
    ],
  },
  {
    slug: "chauffeur-welcome-service",
    group: "service",
    nav: "Chauffeur welcome service",
    title: "Chauffeur Welcome Service App · Airport Pickup Sign and Alerts",
    description: "The chauffeur's airport toolkit: arrival alerts, live location to the exit, car and plate on the guest's page and a digital pickup sign.",
    eyebrow: "Chauffeur welcome",
    h1: "The chauffeur's welcome, done properly.",
    lede: "Your guest sees your name, photo, car and plate before they walk out. You see them coming.",
    top: "Your chauffeur",
    blocks: [
      { h: "Before they land", p: ["Send the link with your booking confirmation. The guest saves it and opens it on landing. Tap On my way when you leave and At Arrivals when you're in place."] },
      { h: "At the airport", p: ["Their taps tell you when to leave the car park. When they're ready, the live map and finding arrow bring you together, and your phone becomes the name sign."] },
      { h: "After the pickup", p: ["Tap We met. Location sharing stops on both phones and the link closes."] },
    ],
    faq: [
      ["Can I show my car?", "Yes: make, colour, plate and a photo."],
      ["Can I save my details for every job?", "Yes. Your name, photo, phone, company and car fill in automatically."],
      ["Is there a dashboard for many jobs?", "Your Greets list shows every pickup and its status."],
    ],
  },

  // ── Tools ──────────────────────────────────────
  {
    slug: "digital-pickup-sign",
    group: "tool",
    nav: "Digital pickup sign",
    title: "Digital Pickup Sign · Free Airport Name Sign Maker",
    description: "Make a digital airport pickup sign in seconds. Type the name, pick a colour, show it full screen on your phone or save it as an image.",
    eyebrow: "Free tool",
    h1: "Digital pickup sign, ready in seconds.",
    lede: "Type their name below. Show it full screen at Arrivals, save it as an image, or turn it into a live Greet.",
    top: "Welcome",
    blocks: [
      { h: "Why a digital sign works better", p: ["Your phone is always with you, the letters are as big as the screen, and it lights up in a dark arrivals hall. With a Greet, the passenger can make it flash from their phone."] },
      { h: "Tips for a sign that gets seen", list: ["Use the name they'll recognise, usually first and last name.", "Hold the phone in landscape, above shoulder height.", "Stand at the end of the barrier where people slow down."] },
      { h: "Sign, then Greet", p: ["The sign is free with no account. Create a Greet when you also want to know when they land and see them walking out."] },
    ],
    faq: [
      ["Is the sign maker free?", "Yes, with no account."],
      ["Can I print it?", "Download it as an image and print it in landscape."],
      ["Will the screen stay on?", "Full-screen mode asks your phone to keep the screen on where the browser allows it."],
    ],
  },
  {
    slug: "airport-welcome-board",
    group: "tool",
    nav: "Airport welcome board",
    title: "Airport Welcome Board Maker · Name Board for Arrivals",
    description: "Create an airport welcome board with your guest's name. Full screen on your phone, download as an image, or connect it to live arrival alerts.",
    eyebrow: "Free tool",
    h1: "An airport welcome board they'll see from the doors.",
    lede: "Big letters, strong colour and their name. Make it below in seconds.",
    top: "Welcome to Athens",
    blocks: [
      { h: "Colour matters", p: ["Most signs at Arrivals are white paper with black marker. A solid Klein Blue board stands out in the row, and so does black with white letters at night."] },
      { h: "Add a line above the name", p: ["Use it for a welcome, your company, or the group name: Welcome to Athens, Skopelos Transfers, Smith Wedding."] },
      { h: "Make it live", p: ["Create a Greet and the board connects to your guest's phone: they can make it flash, and you know when to hold it up."] },
    ],
    faq: [
      ["What size does the image download at?", "2400 × 1350 pixels, sharp enough for a tablet or an A4 print."],
      ["Which colours can I use?", "Klein Blue, white and black."],
      ["Can I use it without the app?", "Yes. The board on this page works on its own."],
    ],
  },
  {
    slug: "airport-greeting-board",
    group: "tool",
    nav: "Airport greeting board generator",
    title: "Airport Greeting Board Generator · Free Name Sign for Arrivals",
    description: "Free airport greeting board generator. Type a name, choose a colour and show it full screen, download it, or turn it into a live pickup.",
    eyebrow: "Free tool",
    h1: "Airport greeting board generator.",
    lede: "Type a name, pick a colour, done. Hold it up full screen or save it as an image.",
    top: "Welcome",
    blocks: [
      { h: "Three ways to use it", list: ["Show it full screen on your phone at Arrivals.", "Download it and print it, or put it on a tablet.", "Create a Greet so the passenger can find it and make it flash."] },
      { h: "Long names", p: ["The board shrinks the letters to fit, so long names and double-barrelled surnames stay on one line."] },
      { h: "Groups and companies", p: ["Use the line above the name for a company, a tour group or a wedding party."] },
    ],
    faq: [
      ["Is it free?", "Yes."],
      ["Does it save the name?", "No. Nothing you type here is stored unless you create a Greet."],
      ["Can I use emoji?", "Yes, though plain names read best from a distance."],
    ],
  },
  {
    slug: "live-flight-arrival-tracker",
    group: "tool",
    nav: "Live flight arrival tracker",
    title: "Live Flight Arrival Tracker for Pickups · Know When They Land",
    description: "Track the flight you're picking up from: delays, new arrival time and landing, plus alerts when your passenger is through and walking out.",
    eyebrow: "Arrival tracking",
    h1: "Know when they land, and when they're really out.",
    lede: "Flight trackers tell you when the wheels touch down. Arigreet also tells you when they've cleared bags and are walking to you.",
    top: "Welcome",
    blocks: [
      { h: "The gap flight trackers miss", p: ["Touchdown to the arrivals doors can take 15 minutes or over an hour, depending on taxiing, passport control and bags. That gap is where most pickups go wrong."] },
      { h: "Flight data plus their taps", list: ["Live flight status: delays, new arrival time and landing.", "I've landed, from the passenger.", "Collecting my bags, so you know to wait.", "I'm ready, when they walk out."] },
      { h: "Alerts on your phone", p: ["Turn on alerts and each step arrives as a notification, even when the app is closed."] },
    ],
    faq: [
      ["Which flights can it track?", "Most scheduled commercial flights, by flight number."],
      ["What if I don't know the flight number?", "Leave it out. The passenger's I've landed tap still tells you."],
      ["Do I get delay alerts?", "Yes, when the arrival time changes."],
    ],
  },
  {
    slug: "passenger-locator",
    group: "tool",
    nav: "Real-time passenger locator",
    title: "Real-Time Passenger Locator for Airport Pickups · No Download",
    description: "See your passenger walking out on a live map, with consent, only during the pickup, and with no app for them to install.",
    eyebrow: "Live finding",
    h1: "See them walking out, live.",
    lede: "When your passenger taps I'm ready, you both see each other on a map. Close up, an arrow points the way.",
    top: "Welcome",
    blocks: [
      { h: "Consent first", p: ["Nothing is shared until the passenger taps I'm ready and allows location. They can stop sharing at any time."] },
      { h: "Map, then arrow", p: ["From far away you see a map with both of you and the distance. Within a short walk, switch to the finding arrow: one big arrow and the metres between you."] },
      { h: "Honest about indoors", p: ["GPS is accurate to a few metres outside and weaker inside terminals. Arigreet shows how accurate the position is, and the meeting point and name board cover the last steps."] },
    ],
    faq: [
      ["Does the passenger need the app?", "No. Location sharing works from their browser."],
      ["How long is location kept?", "It's deleted when you both confirm you've met."],
      ["Can I see them before they're ready?", "No. They decide when to share."],
    ],
  },
  {
    slug: "share-location-without-app",
    group: "tool",
    nav: "No-download location sharing",
    title: "Temporary Location Sharing Link · No App Download Needed",
    description: "Share live location for one pickup with a link. No app, no account, and it stops automatically when you meet.",
    eyebrow: "Location link",
    h1: "A location link that ends when you meet.",
    lede: "Find My and Google Maps sharing need an account, the same app, and remembering to turn it off. A Greet link needs none of that.",
    top: "Welcome",
    blocks: [
      { h: "Made for one meeting", p: ["Sharing starts when the passenger taps I'm ready and stops when you both tap We met. Nothing keeps running in the background afterwards."] },
      { h: "Works on any phone", p: ["iPhone or Android, any modern browser. The passenger never makes an account."] },
      { h: "With the rest of the pickup", p: ["The same link holds the meeting point, your car, a call button and the I can't find you button."] },
    ],
    faq: [
      ["Can I share my own location the same way?", "Yes. Both people share during a live Greet."],
      ["Does it work on iPhone?", "Yes, in Safari and other browsers."],
      ["Is the link public?", "It's a long private link. Only people you send it to can open it."],
    ],
  },
  {
    slug: "terminal-meeting-map",
    group: "tool",
    nav: "Terminal meeting map",
    title: "Terminal Meeting Map · Pick a Meeting Point at Arrivals",
    description: "Agree a meeting point at the terminal before they land, then follow each other on a live map to it.",
    eyebrow: "Meeting point",
    h1: "Agree the spot before they land.",
    lede: "Terminal, arrivals area, exit and a landmark. Your passenger sees it the moment they open your link.",
    top: "Meet at Exit 3",
    blocks: [
      { h: "Pick a point people can find", list: ["The terminal their flight lands at.", "The arrivals hall or area.", "The exit or door number.", "One landmark: a café, a pillar, the information desk."] },
      { h: "I'm at the meeting point", p: ["Each of you can tap to say you're there. Indoors, where GPS is weak, that tap often does more than the map."] },
      { h: "Changing plans", p: ["Move the meeting point and the passenger sees a notice straight away."] },
    ],
    faq: [
      ["Do you have every terminal?", "Terminals for 134 of the busiest airports, and you can type any other."],
      ["Can I add instructions?", "Yes, a short note like 'Wait inside, I'll come to you'."],
      ["Does the map show inside the terminal?", "It shows the airport area. Indoor floor plans aren't included."],
    ],
  },

  // ── Problem guides ─────────────────────────────
  {
    slug: "guides/how-to-find-someone-at-the-airport",
    group: "guide",
    nav: "How to find someone at the airport",
    title: "How to Find Someone at the Airport · A Simple Arrivals Plan",
    description: "A step-by-step plan for finding someone at airport arrivals: before they fly, when they land, and the last 50 metres.",
    eyebrow: "Guide",
    h1: "How to find someone at the airport.",
    lede: "Most missed pickups come down to three things: the wrong terminal, bad timing and no clear meeting point. Here's how to fix all three.",
    top: "Welcome",
    blocks: [
      { h: "Before they fly", list: ["Get the flight number and check which terminal it arrives at.", "Agree one meeting point: exit number plus a landmark.", "Send them a photo of yourself, or a Greet link that has it."] },
      { h: "When they land", list: ["Wait for 'I've landed' before you head to the doors.", "Expect 20 to 45 minutes from landing to the exit, longer with bags or passport queues.", "Ask them to say when they're at the carousel and when they're walking out."] },
      { h: "The last 50 metres", list: ["Stand still at the agreed point. Two people moving rarely meet.", "Hold up a name sign at head height.", "Share live location for the final walk, then switch it off."] },
    ],
    faq: [
      ["What's the best place to meet at arrivals?", "Just outside the doors passengers walk through, at a fixed landmark, away from the barrier crush."],
      ["Should I wait inside or outside?", "Inside the arrivals hall, unless your airport only allows pickups at the kerb."],
      ["What if their phone doesn't work abroad?", "Airport Wi-Fi is enough for the Greet page. Their taps also wait and send when they connect."],
    ],
  },
  {
    slug: "guides/where-to-meet-at-arrivals",
    group: "guide",
    nav: "Where to meet at arrivals",
    title: "Where to Meet at Airport Arrivals · Pick a Spot That Works",
    description: "How to choose a meeting point at the arrivals terminal that both of you can find, even with no signal.",
    eyebrow: "Guide",
    h1: "Where to meet at arrivals.",
    lede: "Pick a spot that's easy to describe, easy to see from the doors and quiet enough to stand still.",
    top: "Meet me here",
    blocks: [
      { h: "Good meeting points", list: ["A numbered exit or door.", "A café or shop sign that's visible from the doors.", "The information desk.", "A specific pillar or meeting-point sign, if the airport has one."] },
      { h: "Bad meeting points", list: ["'Arrivals', with no detail.", "The barrier itself, where everyone crowds.", "Outside at the kerb, where cars can't stop for long."] },
      { h: "Write it down once", p: ["Put the meeting point in the Greet and it's on their screen the whole time, even with no signal."] },
    ],
    faq: [
      ["What if the airport has several terminals?", "Check the arrival terminal on their booking. Each terminal has its own arrivals hall."],
      ["Can I change the spot later?", "Yes. They'll see it changed."],
      ["Is there a page for my airport?", "We have arrival guides for the busiest airports. See the airports list."],
    ],
  },
  {
    slug: "guides/lost-at-airport-arrivals",
    group: "guide",
    nav: "Lost at airport arrivals",
    title: "Lost at Airport Arrivals? What to Do in the Next Five Minutes",
    description: "Can't find the person picking you up? A calm plan for when you're lost at airport arrivals.",
    eyebrow: "Guide",
    h1: "Lost at arrivals? Do this.",
    lede: "Stop walking. Moving makes it harder for both of you. Then work through these steps.",
    top: "Over here",
    blocks: [
      { h: "Right now", list: ["Stand still somewhere visible, near the exit you came out of.", "Connect to the airport Wi-Fi if you have no signal.", "Tell your greeter which exit or door you're at."] },
      { h: "If you have a Greet link", list: ["Tap I can't find my greeter. Their name board lights up.", "Open the finding arrow and walk the way it points.", "Look for the board flashing."] },
      { h: "If nothing works", p: ["Go to the information desk and ask them to call or page your driver. Keep the booking details handy."] },
    ],
    faq: [
      ["My phone has no signal. What now?", "Use airport Wi-Fi. If you opened your Greet link before, the meeting point is still on your screen."],
      ["My driver isn't answering.", "Stay at the meeting point for 15 minutes before moving, then contact the booking company."],
      ["I came out of the wrong exit.", "Tell your greeter the exit number and stay put. They'll come to you."],
    ],
  },
  {
    slug: "guides/cant-find-my-driver-at-the-airport",
    group: "guide",
    nav: "Missing my driver at the airport",
    title: "Can't Find Your Driver at the Airport? Here's What to Do",
    description: "Missing your driver at the airport? Steps to find them fast, and how drivers can stop it happening.",
    eyebrow: "Guide",
    h1: "Can't find your driver at the airport?",
    lede: "It's usually the wrong exit or bad timing. Both are fixable in a couple of minutes.",
    top: "Your driver",
    blocks: [
      { h: "For passengers", list: ["Check your booking for the meeting point and driver's number.", "Message or call with the exit number you're at.", "Stand still, look for your name, and give it ten minutes."] },
      { h: "For drivers", list: ["Send a Greet link with your photo, car and exact meeting point.", "Wait for I've landed and Collecting my bags before walking in.", "Hold up the name board when they tap I'm ready."] },
      { h: "Why it keeps happening", p: ["Drivers wait at one door, passengers come out of another, and phones die or have no signal. A shared pickup page with a fixed meeting point removes most of it."] },
    ],
    faq: [
      ["How long should a driver wait?", "Most companies include 45 to 60 minutes of free waiting after landing. Check your booking."],
      ["What if my flight was delayed?", "With the flight number in the Greet, your driver sees the new arrival time."],
      ["Can I see where my driver is?", "Yes, once you tap I'm ready and both of you share location."],
    ],
  },
  {
    slug: "guides/coordinating-airport-pickups",
    group: "guide",
    nav: "Coordinating airport pickups",
    title: "Coordinating Airport Pickups · A Checklist That Works",
    description: "A practical checklist for coordinating airport pickups for guests, clients and family.",
    eyebrow: "Guide",
    h1: "Coordinating airport pickups: the checklist.",
    lede: "Everything to sort out before, during and after the pickup.",
    top: "Welcome",
    blocks: [
      { h: "Before the day", list: ["Flight number and arrival terminal.", "Passenger's phone number and language.", "Meeting point with exit and landmark.", "Your photo and, if driving, your car and plate."] },
      { h: "On the day", list: ["Check the flight before leaving.", "Tell them you're on your way.", "Wait for landed and bags before going in.", "Board up when they're ready."] },
      { h: "Afterwards", p: ["Confirm you've met. If you run pickups every week, save your details once so each new Greet takes a minute."] },
    ],
    faq: [
      ["How early should I arrive?", "Aim to be in place 15 to 20 minutes after landing for flights without checked bags, 30 to 45 with bags."],
      ["What should I send the passenger?", "One link with everything in it: who, where, the car and a way to call."],
      ["Can I manage several pickups?", "Yes. Your Greets list shows each one and its status."],
    ],
  },

  // ── Professionals ──────────────────────────────
  {
    slug: "for/chauffeurs",
    group: "pro",
    nav: "Corporate driver greeting app",
    title: "Airport Pickup App for Chauffeurs and Corporate Drivers",
    description: "Arrival alerts, live finding and a digital pickup sign for chauffeurs and corporate drivers. Your car and plate on the passenger's page.",
    eyebrow: "For chauffeurs",
    h1: "Pickups that start on time, every time.",
    lede: "Know when your passenger is through, walk in at the right moment, and hold up a sign they'll spot first.",
    top: "Your chauffeur",
    blocks: [
      { h: "Less waiting in the car park", p: ["Wait for Collecting my bags before you walk in. Your phone buzzes when they're ready."] },
      { h: "Look professional", p: ["Your name, photo, company and car are on the passenger's page. The name board looks sharper than a paper sign."] },
      { h: "Fewer no-shows", p: ["Passengers can't miss you when they can follow an arrow to you and make your board flash."] },
    ],
    faq: [
      ["Can my company name show?", "Yes, on the passenger's page and on the board."],
      ["Do I need to type my details each time?", "No. Save them once in your profile."],
      ["Does it work for back-to-back jobs?", "Yes. Each pickup is its own Greet."],
    ],
  },
  {
    slug: "for/limousine-companies",
    group: "pro",
    nav: "Limousine pickup sign",
    title: "Limousine Pickup Sign and Arrival Alerts · Arigreet",
    description: "A digital limousine pickup sign plus live arrival alerts and passenger finding for limousine and executive car companies.",
    eyebrow: "For limousine companies",
    h1: "A limousine welcome that matches the car.",
    lede: "A clean name board, your company on it, and a passenger who walks straight to your driver.",
    top: "Your company name",
    blocks: [
      { h: "On brand", p: ["Put your company above the guest's name on the board, and on the guest's pickup page."] },
      { h: "Driver and dispatcher", p: ["Drivers run each pickup from their phone. Each Greet shows its status: opened, landed, bags, ready, met."] },
      { h: "Guests from anywhere", p: ["The guest's page speaks seven languages and needs no app."] },
    ],
    faq: [
      ["Can I add our logo?", "Your company name shows today. Logos are on the way."],
      ["Can the guest call the driver?", "Yes, if you add the number."],
      ["Do guests need an account?", "No."],
    ],
  },
  {
    slug: "for/hotels",
    group: "pro",
    nav: "Hotel transfer coordinator",
    title: "Hotel Airport Transfer Coordination · Arigreet for Hotels",
    description: "Coordinate hotel airport transfers: send guests a pickup link with your driver and car, get arrival alerts and greet them by name.",
    eyebrow: "For hotels",
    h1: "Hotel transfers your guests talk about.",
    lede: "Send the pickup link with the booking. Your driver knows when they land; the guest knows who's coming.",
    top: "Welcome to the hotel",
    blocks: [
      { h: "The welcome starts at the airport", p: ["Guests judge the stay from the first face they see. A named driver, a clear meeting point and a board with their name sets the tone."] },
      { h: "For the front desk", p: ["Create the Greet when the transfer is booked. Add the guest's language and flight, then send the link by email or WhatsApp."] },
      { h: "For the driver", p: ["Alerts for landed, bags and ready. A live map and a name board when it's time."] },
    ],
    faq: [
      ["Can we send it with our confirmation email?", "Yes. Paste the link into any email or message."],
      ["What language does the guest see?", "Their phone's language, from seven, and they can switch it."],
      ["Does the guest need to install anything?", "No."],
    ],
  },
  {
    slug: "for/airport-shuttles",
    group: "pro",
    nav: "Airport shuttle tracker",
    title: "Airport Shuttle Pickup Tracker · Arrival Alerts for Shuttles",
    description: "Know when each shuttle passenger has landed and is ready. Give them a clear meeting point and a sign to look for.",
    eyebrow: "For shuttles",
    h1: "Fill the shuttle without the headcount panic.",
    lede: "Each passenger gets a link. You see who's landed, who's at bags and who's walking out.",
    top: "Shuttle to the city",
    blocks: [
      { h: "One link per passenger", p: ["Create a Greet for each traveller with their flight. Their taps show up on your list."] },
      { h: "A sign for the group", p: ["Use the line above the name for the shuttle or tour name, and the name line for the group."] },
      { h: "Honest limits", p: ["Arigreet is built for one passenger per link today. Group pickups work as several Greets."] },
    ],
    faq: [
      ["Can one link cover a whole group?", "Not yet. Create one Greet per passenger."],
      ["Can passengers see each other?", "No. Each link is private."],
      ["Can I show the vehicle?", "Yes, with colour and plate."],
    ],
  },
  {
    slug: "for/corporate-travel",
    group: "pro",
    nav: "Corporate travel pickups",
    title: "Corporate Travel Airport Pickups · Arigreet",
    description: "Make sure visiting executives, clients and new hires are met at the airport, with alerts, live finding and a professional name board.",
    eyebrow: "For corporate travel",
    h1: "Every visitor met, on time.",
    lede: "Clients, executives and new hires walk out to a named person holding a clean sign.",
    top: "Welcome to the company",
    blocks: [
      { h: "For office managers", p: ["Create the Greet when the trip is booked and send the link to the traveller. The driver or colleague runs it on the day."] },
      { h: "For travellers", p: ["No app, no account, one page with the person meeting them and where."] },
      { h: "Privacy", p: ["Location is only shared during the pickup and deleted after it."] },
    ],
    faq: [
      ["Can colleagues share pickups?", "Each person runs pickups from their own account."],
      ["Is it GDPR-friendly?", "Location is shared only with consent and deleted after the pickup; finished pickups are removed after 30 days."],
      ["Does it cost anything?", "Personal use is free. Talk to us about company use."],
    ],
  },

  // ── Consumers ──────────────────────────────────
  {
    slug: "for/families",
    group: "home",
    nav: "Picking up family at the airport",
    title: "Picking Up Family at the Airport · Arigreet",
    description: "Picking up family at the airport? Know when they land, show them where you are and find each other fast. Free and nothing for them to install.",
    eyebrow: "For families",
    h1: "Picking up family at the airport, minus the stress.",
    lede: "Your mum taps I've landed. You know. She sees exactly where you're standing.",
    top: "Welcome home",
    blocks: [
      { h: "Made for parents and grandparents", p: ["One big button at a time, in their language. No app, no password, nothing to set up."] },
      { h: "For you", p: ["Wait in the café until they tap Collecting my bags. Walk to the doors when they tap I'm ready."] },
      { h: "A sign they'll smile at", p: ["Put Welcome home above their name and hold your phone up."] },
    ],
    faq: [
      ["Is it free?", "Yes, for personal pickups."],
      ["My dad isn't good with phones.", "The page has one button at a time and big text. Send the link the day before so he's seen it."],
      ["What if their phone dies?", "Agree the meeting point in the Greet beforehand. It's the fallback."],
    ],
  },
  {
    slug: "for/picking-up-friends",
    group: "home",
    nav: "Friend arrival tracker",
    title: "Friend Arrival Tracker · Pick Up Friends at the Airport",
    description: "Picking up a friend at the airport? See when they land and walk out, and find each other in seconds.",
    eyebrow: "For friends",
    h1: "Pick up your friend without the 'where are you?' texts.",
    lede: "They tap, you know. Then you find each other with a map and an arrow.",
    top: "Finally!",
    blocks: [
      { h: "Make it a moment", p: ["Put something fun above their name on the board. They'll see it from the doors."] },
      { h: "No app for them", p: ["They open your link in their browser. That's it."] },
      { h: "Done when you meet", p: ["Tap We met and location sharing stops."] },
    ],
    faq: [
      ["Do they need to sign up?", "No."],
      ["Do I need an account?", "Yes, a quick one, so you can see their updates and get alerts."],
      ["Can I meet them somewhere other than arrivals?", "Yes. Set any meeting point."],
    ],
  },
  {
    slug: "for/holiday-arrivals",
    group: "home",
    nav: "Holiday airport pickup tool",
    title: "Holiday Airport Pickup Tool · Meet Guests on Holiday",
    description: "Meeting guests for a holiday, wedding or villa stay? Send one link, know when they land and greet them with a name board.",
    eyebrow: "For holidays",
    h1: "Holiday starts at Arrivals.",
    lede: "Villa hosts, wedding parties and families meeting friends abroad: one link each, one sign, no chaos.",
    top: "Welcome to Greece",
    blocks: [
      { h: "For villa and island hosts", p: ["Send each booking a Greet with your photo and the meeting point. Small island airports get busy when several flights land together."] },
      { h: "For weddings and group trips", p: ["Use the line above the name for the occasion: Anna & Nikos, Smith Family Reunion."] },
      { h: "In their language", p: ["Guests see the page in English, Greek, French, Spanish, Italian, German or Portuguese."] },
    ],
    faq: [
      ["Does it work at small island airports?", "Yes, at any airport. We have arrival guides for many of them."],
      ["Can I greet several guests?", "Create one Greet per guest or couple."],
      ["Is it free?", "Yes, for personal use."],
    ],
  },
  {
    slug: "for/family-flight-sync",
    group: "home",
    nav: "Family flight sync",
    title: "Family Flight Sync · Track Your Family's Arrival",
    description: "Keep the family in sync on arrival day: flight status, landed and ready alerts, and a live map when they walk out.",
    eyebrow: "For families",
    h1: "Everyone on the same page on arrival day.",
    lede: "Add the flight, send the link, and follow along from landing to hello.",
    top: "Welcome home",
    blocks: [
      { h: "The flight", p: ["With live flight tracking on, you see delays and the new arrival time."] },
      { h: "The person", p: ["Their taps tell you what the flight can't: through passport control, at bags, walking out."] },
      { h: "The meeting", p: ["Map, arrow and name board for the last few metres."] },
    ],
    faq: [
      ["Can two family members follow the same pickup?", "The person who creates the Greet runs it. Share the meeting point with others."],
      ["What if the flight is diverted?", "The flight status shows it, and the passenger can still tap when they land."],
      ["Is location shared before landing?", "No. Only after they tap I'm ready."],
    ],
  },
];
