/* Arrival terminals for the world's busiest and most-requested airports.
   Hand-checked and kept short; anything missing can still be typed.
   Single-terminal airports are listed so the picker can say so. */
export const TERMINALS = {
  // Europe
  LHR: ["Terminal 2", "Terminal 3", "Terminal 4", "Terminal 5"],
  LGW: ["North Terminal", "South Terminal"],
  STN: ["Main Terminal"],
  LTN: ["Main Terminal"],
  LCY: ["Main Terminal"],
  EDI: ["Main Terminal"],
  DUB: ["Terminal 1", "Terminal 2"],
  CDG: ["Terminal 1", "Terminal 2A", "Terminal 2B", "Terminal 2C", "Terminal 2D", "Terminal 2E", "Terminal 2F", "Terminal 2G", "Terminal 3"],
  ORY: ["Orly 1-2", "Orly 3", "Orly 4"],
  NCE: ["Terminal 1", "Terminal 2"],
  AMS: ["Schiphol Plaza"],
  BRU: ["Main Terminal"],
  FRA: ["Terminal 1", "Terminal 2", "Terminal 3"],
  MUC: ["Terminal 1", "Terminal 2"],
  BER: ["Terminal 1", "Terminal 2"],
  DUS: ["Main Terminal"],
  ZRH: ["Airport Centre"],
  GVA: ["Main Terminal"],
  VIE: ["Terminal 1", "Terminal 3"],
  MAD: ["Terminal 1", "Terminal 2", "Terminal 3", "Terminal 4", "Terminal 4S"],
  BCN: ["Terminal 1", "Terminal 2"],
  AGP: ["Terminal 2", "Terminal 3"],
  PMI: ["Main Terminal"],
  LIS: ["Terminal 1", "Terminal 2"],
  OPO: ["Main Terminal"],
  FCO: ["Terminal 1", "Terminal 3"],
  MXP: ["Terminal 1", "Terminal 2"],
  VCE: ["Main Terminal"],
  NAP: ["Main Terminal"],
  ATH: ["Main Terminal"],
  SKG: ["Main Terminal"],
  HER: ["Main Terminal"],
  JTR: ["Main Terminal"],
  JMK: ["Main Terminal"],
  JSI: ["Main Terminal"],
  CFU: ["Main Terminal"],
  RHO: ["Main Terminal"],
  IST: ["Main Terminal"],
  SAW: ["Main Terminal"],
  AYT: ["Terminal 1", "Terminal 2", "Domestic Terminal"],
  CPH: ["Terminal 2", "Terminal 3"],
  ARN: ["Terminal 2", "Terminal 3", "Terminal 4", "Terminal 5"],
  OSL: ["Main Terminal"],
  HEL: ["Terminal 1", "Terminal 2"],
  WAW: ["Main Terminal"],
  PRG: ["Terminal 1", "Terminal 2"],
  BUD: ["Terminal 2A", "Terminal 2B"],
  // Middle East
  DXB: ["Terminal 1", "Terminal 2", "Terminal 3"],
  DWC: ["Main Terminal"],
  AUH: ["Terminal A"],
  DOH: ["Hamad International"],
  BAH: ["Main Terminal"],
  KWI: ["Terminal 1", "Terminal 4", "Terminal 5"],
  MCT: ["Main Terminal"],
  RUH: ["Terminal 1", "Terminal 2", "Terminal 3", "Terminal 4", "Terminal 5"],
  JED: ["Terminal 1", "North Terminal", "Hajj Terminal"],
  TLV: ["Terminal 1", "Terminal 3"],
  AMM: ["Main Terminal"],
  // Africa
  LOS: ["International Terminal (new)", "International Terminal (old)", "Domestic MMA1", "Domestic MMA2"],
  ABV: ["International Terminal", "Domestic Terminal"],
  PHC: ["International Terminal", "Domestic Terminal"],
  KAN: ["International Terminal", "Domestic Terminal"],
  BNI: ["Main Terminal"],
  ACC: ["Terminal 3 (International)", "Terminal 2 (Domestic)"],
  NBO: ["Terminal 1A", "Terminal 1B", "Terminal 1C", "Terminal 1D", "Terminal 1E"],
  ADD: ["Terminal 1", "Terminal 2"],
  JNB: ["Terminal A (International)", "Terminal B (Domestic)"],
  CPT: ["Central Terminal"],
  DUR: ["Main Terminal"],
  CAI: ["Terminal 1", "Terminal 2", "Terminal 3"],
  CMN: ["Terminal 1", "Terminal 2"],
  RAK: ["Terminal 1", "Terminal 2"],
  DSS: ["Main Terminal"],
  KGL: ["Main Terminal"],
  DAR: ["Terminal 3"],
  EBB: ["Main Terminal"],
  // Asia and Pacific
  SIN: ["Terminal 1", "Terminal 2", "Terminal 3", "Terminal 4"],
  HKG: ["Terminal 1"],
  NRT: ["Terminal 1", "Terminal 2", "Terminal 3"],
  HND: ["Terminal 1", "Terminal 2", "Terminal 3"],
  KIX: ["Terminal 1", "Terminal 2"],
  ICN: ["Terminal 1", "Terminal 2"],
  PEK: ["Terminal 2", "Terminal 3"],
  PKX: ["Main Terminal"],
  PVG: ["Terminal 1", "Terminal 2"],
  CAN: ["Terminal 1", "Terminal 2"],
  TPE: ["Terminal 1", "Terminal 2"],
  BKK: ["Main Terminal"],
  DMK: ["Terminal 1 (International)", "Terminal 2 (Domestic)"],
  KUL: ["KLIA Terminal 1", "KLIA Terminal 2"],
  CGK: ["Terminal 1", "Terminal 2", "Terminal 3"],
  DPS: ["International Terminal", "Domestic Terminal"],
  MNL: ["Terminal 1", "Terminal 2", "Terminal 3"],
  DEL: ["Terminal 1", "Terminal 2", "Terminal 3"],
  BOM: ["Terminal 1", "Terminal 2"],
  BLR: ["Terminal 1", "Terminal 2"],
  SYD: ["T1 International", "T2 Domestic", "T3 Domestic"],
  MEL: ["T1", "T2 International", "T3", "T4"],
  BNE: ["International Terminal", "Domestic Terminal"],
  AKL: ["International Terminal", "Domestic Terminal"],
  // Americas
  JFK: ["Terminal 1", "Terminal 4", "Terminal 5", "Terminal 7", "Terminal 8"],
  EWR: ["Terminal A", "Terminal B", "Terminal C"],
  LGA: ["Terminal A", "Terminal B", "Terminal C"],
  BOS: ["Terminal A", "Terminal B", "Terminal C", "Terminal E"],
  IAD: ["Main Terminal"],
  DCA: ["Terminal 1", "Terminal 2"],
  PHL: ["Terminal A", "Terminal B", "Terminal C", "Terminal D", "Terminal E", "Terminal F"],
  ATL: ["Domestic Terminal", "International Terminal"],
  MIA: ["North Terminal", "Central Terminal", "South Terminal"],
  MCO: ["Terminal A", "Terminal B", "Terminal C"],
  ORD: ["Terminal 1", "Terminal 2", "Terminal 3", "Terminal 5"],
  DTW: ["McNamara Terminal", "Evans Terminal"],
  MSP: ["Terminal 1", "Terminal 2"],
  DFW: ["Terminal A", "Terminal B", "Terminal C", "Terminal D", "Terminal E"],
  IAH: ["Terminal A", "Terminal B", "Terminal C", "Terminal D", "Terminal E"],
  DEN: ["Main Terminal"],
  PHX: ["Terminal 3", "Terminal 4"],
  LAS: ["Terminal 1", "Terminal 3"],
  LAX: ["Tom Bradley International", "Terminal 1", "Terminal 2", "Terminal 3", "Terminal 4", "Terminal 5", "Terminal 6", "Terminal 7", "Terminal 8"],
  SFO: ["International Terminal", "Terminal 1", "Terminal 2", "Terminal 3"],
  SAN: ["Terminal 1", "Terminal 2"],
  SEA: ["Main Terminal"],
  CLT: ["Main Terminal"],
  YYZ: ["Terminal 1", "Terminal 3"],
  YVR: ["Main Terminal"],
  YUL: ["Main Terminal"],
  MEX: ["Terminal 1", "Terminal 2"],
  CUN: ["Terminal 2", "Terminal 3", "Terminal 4"],
  GRU: ["Terminal 1", "Terminal 2", "Terminal 3"],
  GIG: ["Terminal 1", "Terminal 2"],
  EZE: ["Terminal A", "Terminal B", "Terminal C"],
  BOG: ["Terminal 1"],
  SCL: ["International Terminal", "Domestic Terminal"],
  LIM: ["Main Terminal"],
};

/* Shown before anyone types: the busiest hubs plus Greece, where Arigreet starts. */
export const POPULAR = [
  "ATH", "SKG", "HER", "JTR", "JMK", "JSI",
  "LHR", "LGW", "CDG", "AMS", "FRA", "MUC", "MAD", "BCN", "FCO", "IST",
  "DXB", "DOH", "AUH",
  "LOS", "ABV", "ACC", "NBO", "JNB", "CAI",
  "JFK", "EWR", "LAX", "MIA", "ORD", "ATL", "YYZ",
  "SIN", "HKG", "NRT", "ICN", "BKK", "DEL", "SYD",
];
